Add yarn
seegno/docker-node pull request #23
Opened 2016-11-04 16:15 UTC by promag

2016-11-04 16:21 UTC, ruimarinho requested changes

2016-11-04 16:21 UTC, ruimarinho commented on 4/onbuild-yarn/Dockerfile
> +ONBUILD RUN yarn --ignore-scripts
Do we still need this (--ignore-scripts)?

2016-11-04 16:21 UTC, ruimarinho commented on 4/onbuild-yarn/Dockerfile
> +  && tar zxvf yarn-${YARN_VERSION}.tar.gz
Move to its own fancy directory?

2016-11-04 16:21 UTC, ruimarinho commented on 4/onbuild-yarn/Dockerfile
> +RUN apk --no-cache --virtual build-dependencies add g++ gcc git make python
Move up since we'll update yarn far more than these dependencies?

2016-11-04 16:21 UTC, ruimarinho commented on 4/onbuild-yarn/Dockerfile
> +ENV PATH /dist/bin/:$PATH
Move up?

2016-11-04 16:52 UTC, promag commented on 4/onbuild-yarn/Dockerfile
> +  && tar zxvf yarn-${YARN_VERSION}.tar.gz
Delete archive after `tar zx`.

2016-11-07 10:49 UTC, ruimarinho requested changes

2016-11-07 10:49 UTC, ruimarinho commented on 6/slim-yarn/Dockerfile
> +RUN apk --no-cache --virtual yarn-dependencies add ca-certificates openssl \
add `tar` here so that a newly updated version is installed.

2016-11-07 10:49 UTC, ruimarinho commented on 6/slim-yarn/Dockerfile
> +  && wget https://github.com/yarnpkg/yarn/releases/download/${YARN_VERSION}/yarn-${YARN_VERSION}.tar.gz \
`wget -O - https://github.com/yarnpkg/yarn/releases/download/${YARN_VERSION}/yarn-${YARN_VERSION}.tar.gz | tar -C /usr/local/lib/yarn/ --strip-components 1 -zxvf -`

2016-11-07 11:24 UTC, promag commented
For reference, this is the diff between npm and yarn.

```diff
diff 7/slim/Dockerfile 7/slim-yarn/Dockerfile
1c1
< FROM mhart/alpine-node:7
---
> FROM mhart/alpine-node:base-7
5a6,16
> # Add yarn.
> ARG YARN_VERSION=v0.16.1
>
> ENV PATH /usr/local/lib/yarn/bin/:$PATH
>
> RUN apk --no-cache --virtual yarn-dependencies add ca-certificates openssl tar \
>   && update-ca-certificates \
>   && mkdir /usr/local/lib/yarn/ \
>   && wget -O - https://github.com/yarnpkg/yarn/releases/download/${YARN_VERSION}/yarn-${YARN_VERSION}.tar.gz | tar -C /usr/local/lib/yarn/ --strip-components 1 -zxvf - \
>   && apk del yarn-dependencies
>
18,19c29,30
< # Copy package.json and npm-shrinkwrap.json if they exist.
< ONBUILD COPY *.json ./
---
> # Copy package.json and yarn.lock if they exist.
> ONBUILD COPY *package.json *yarn.lock ./
```

2016-11-07 11:46 UTC, ruimarinho requested changes

2016-11-07 11:46 UTC, ruimarinho commented on 7/test-yarn/Dockerfile
> +ARG YARN_VERSION v0.16.1
Missing `=`.

2016-11-07 11:49 UTC, ruimarinho requested changes

2016-11-07 11:49 UTC, ruimarinho commented on 4/test-yarn/Dockerfile
> +ARG YARN_VERSION v0.16.1
Missing `=`.

2016-11-07 11:49 UTC, ruimarinho commented on 5/test-yarn/Dockerfile
> +ARG YARN_VERSION v0.16.1
Missing `=`.

2016-11-07 13:31 UTC, ruimarinho approved these changes

2016-11-07 13:32 UTC, merged